### ISSUE TITLE
sqlite3.IntegrityError: NOT NULL constraint failed: Events.eve_IP

### ISSUE THREAD

**Issue by ncmoud** [pucherot/Pi.Alert#2]
Sorry if this report is too soon after the last one, but this happens in v2.51.
```
Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 1311, in <module>
    sys.exit(main())
  File "/home/pi/pialert/back/pialert.py", line 72, in main
    res = scan_network()
  File "/home/pi/pialert/back/pialert.py", line 375, in scan_network
    create_new_devices ()
  File "/home/pi/pialert/back/pialert.py", line 657, in create_new_devices
    (startTime, ) )
sqlite3.IntegrityError: NOT NULL constraint failed: Events.eve_IP
```
It also looks like the Devices database is read-only.

**Comment by pucherot** [comment]
On the contrary, thanks you very much for the report.

I have released a new version v2.52 that solves the bug.
The problem is that Pi.hole has some devices without last known IP address (this does not happen in my network).
In your case, it's enough to copy file "back/pialert.py" again.

BR

**Comment by ncmoud** [comment]
Looks like it works now.
![image](https://user-images.githubusercontent.com/40201919/104199883-48b24600-5428-11eb-8e94-87b6cc7ed501.png)

**Comment by ncmoud** [comment]
Looks like there is still an issue in the database.
`attempt to write a readonly database`

**Comment by pucherot** [comment]
New issue #3 created with this new report.

**Comment by pucherot** [comment]
OK, we need to add permission to the Lighttpd (web server) user.

There are 2 possibilities:

## 1
~~~
chmod -R 766 ~/pialert/db
~~~

## 2
~~~
sudo chgrp -R www-data ~/pialert/db
chmod -R 760 ~/pialert/db
~~~

I think both options are valid.
